EXECUTABLE := gemm.exe
CUFILES := gemm.cu
# EXECUTABLE := gemm.exe
# CUFILES := gemm_own_shared_working.cu
# CUFILES := gemm_ws.cu

# EXECUTABLE := gemm.exe
# CUFILES := gemm_tensor_shared_rajat.cu

include ../common.mk
