# EXECUTABLE := mvt.exe
# CUFILE := mvt.cu

# EXECUTABLE := mvt_shared.exe
# CUFILE := mvt_shared.cu

# EXECUTABLE := mvt_shared_testing.exe
# CUFILE := mvt_shared_testing.cu

# EXECUTABLE := mvt_shared_new.exe
# CUFILE := mvt_shared_new.cu

# EXECUTABLE := mvt_ws.exe
# CUFILE := mvt_ws.cu

# EXECUTABLE := mvt_K1_ws_loading_y.exe
# CUFILE := mvt_K1_ws_loading_y.cu

EXECUTABLE := mvt_K1_ws_loading_y_testing.exe
CUFILE := mvt_K1_ws_loading_y_testing.cu

# EXECUTABLE := mvt_K1_ws_loading_A_and_y.exe
# CUFILE := mvt_K1_ws_loading_A_and_y.cu

# EXECUTABLE := mvt_K1_ws_loading_A_and_y_parallelDMA.exe
# CUFILE := mvt_K1_ws_loading_A_and_y_parallelDMA.cu

#  ***************

# EXECUTABLE := mvt_K2_ws_loading_y.exe
# CUFILE := mvt_K2_ws_loading_y.cu


include ../common.mk